#!/usr/bin/env ruby

puts "🔍 Manual testing of sidebar components..."
puts "1. Grid component (OLD syntax - should fail):"
puts "   grid(cols: 3, gap: 16) do"
puts "     # Add grid items here"
puts "   end"
puts ""
puts "2. Grid component (NEW syntax - should work):"
puts "   grid(columns: 3, spacing: 16) do"
puts "     (1..6).each do |i|"
puts "       card(elevation: 1) do"
puts "         text(\"Grid Item #{i}\")"
puts "       end"
puts "     end"
puts "   end"
puts ""
puts "3. VStack component (IMPROVED):"
puts "   vstack(spacing: 16) do"
puts "     text(\"First Item\")"
puts "     text(\"Second Item\")"
puts "     text(\"Third Item\")"
puts "   end"
puts ""
puts "4. Card component (IMPROVED):"
puts "   card(elevation: 2) do"
puts "     text(\"Card Title\")"
puts "       .font_size(\"xl\")"
puts "       .font_weight(\"bold\")"
puts "     text(\"Card content goes here\")"
puts "       .text_color(\"gray-600\")"
puts "   end"
puts ""
puts "5. Form component (IMPROVED):"
puts "   form(action: \"#\", method: :post) do"
puts "     textfield(name: \"email\", placeholder: \"Enter email\")"
puts "       .w(\"full\")"
puts "       .mb(4)"
puts "     button(\"Submit\", type: \"submit\")"
puts "       .bg(\"blue-500\")"
puts "       .text_color(\"white\")"
puts "       .px(4).py(2)"
puts "       .rounded(\"lg\")"
puts "   end"
puts ""
puts "✅ All sidebar components have been updated with proper syntax!"
puts "Visit http://localhost:3000 to test them in the playground."